[package]
name = "kelp-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
tower-lsp = "0.20.0"
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread", "io-std"] }
parser-rs = { workspace = true }
kelp-core = { workspace = true }
kelp-parser = { workspace = true }
