[package]
name = "kelp-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
kelp-core = { workspace = true }
ordered-float = { workspace = true }
minecraft-command-types = { workspace = true }
nonempty = { workspace = true }
serde_json = { workspace = true }
paste = "1.0.15"
phf = "0.13.1"
