[package]
name = "kelp-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
nonempty = { workspace = true }
kelp-core = { workspace = true }
kelp-parser = { workspace = true }
ariadne = "0.6.0"
yansi = "1.0.1"
clap = { version = "4.5.53", features = ["derive"] }
dirs = "6.0.0"
