[package]
name = "kelp-core"
version = "0.1.0"
edition = "2024"

[dependencies]
minecraft-command-types = { workspace = true }
minecraft-command-types_derive = { workspace = true }
parser-rs = { workspace = true }
nonempty = { workspace = true }
ordered-float = { workspace = true }
serde_json = "1.0.145"
strum = "0.27.2"
strum_macros = "0.27.2"
